baseURL = "http://example.org/"
languageCode = "en-us"
title = "Javier Robalino"
theme = "osprey"

[Params]
    tagline = "Front End & VR/AR Developer"
    copyright = true
    logoBig = "/images/monkey-big.png"
    logoSmall = "/images/monkey-small.jpg"
    favicon = "favicon.ico"

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
# [[menu.main]]
#    name = "Blog"
#    url  = "/#blog"
#    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4